# Generated by Django 4.2.14 on 2024-07-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="description", new_name="body",
        ),
    ]
