# Generated by Django 4.2.14 on 2024-07-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_rename_description_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="subtitle",
            field=models.CharField(default="-", max_length=400),
        ),
    ]
